### ISSUE TITLE
pooling connection and connection string mismatch [3:44pm]

### ISSUE THREAD

**Issue by alloursjournall** [frankcollins3/Next-Mine-Nugget#2]
**attempting to do:**
pool connections .split() not working.

**error:**
➜  Next-Mine-Nugget git:(main) ✗ node seed.js
/Users/me/Desktop/Next-Mine-Nugget/db.js:8
const [host, portAndDatabase] = hostAndDb.split(':');
                                          ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/Users/me/Desktop/Next-Mine-Nugget/db.js:8:43)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/me/Desktop/Next-Mine-Nugget/seed.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
➜  Next-Mine-Nugget git:(main) ✗

**proposed approach:**
hard code name values.

**Comment by alloursjournall** [comment]
hard coded string values intead of splitting and performing regex upon connection string
[4:00ishpm]
